NUBIA_PARTS_PATH := packages/apps/NubiaParts

PRODUCT_SOONG_NAMESPACES += $(NUBIA_PARTS_PATH)

BOARD_VENDOR_SEPOLICY_DIRS += $(NUBIA_PARTS_PATH)/sepolicy/vendor
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(NUBIA_PARTS_PATH)/sepolicy/public
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(NUBIA_PARTS_PATH)/sepolicy/private